swagger:
  enabled : true
  title : 框架
  description : 框架接口文档
  license : Powered
  licenseUrl : http://localhost
  version : 版本号:V1.0.0
  termsOfServiceUrl : http://localhost
  contact:
    name: cgli
    email: cgli@qq.com
    url: http://localhost
  needAuth : true
#增加下面属性防止swagger页面无法查看接口，报错no operations defined in spec错误
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER